implemented the la_consensusState api
LATOKEN/lachain pull request #179
Opened 2022-01-31 08:57 UTC by dushyantb

2022-01-31 10:51 UTC, sgladkov requested changes

2022-01-31 10:51 UTC, sgladkov commented on src/Lachain.Core/Consensus/ConsensusManager.cs
> +        public EraBroadcaster GetEras(long era)
I think it is a misleading name. Use GetEraBroadcaster  or smth like this please

2022-01-31 10:51 UTC, sgladkov commented on src/Lachain.Core/RPC/HTTP/Web3/BlockchainServiceWeb3.cs
> +        private JArray GetConsensusState(long era)
This call should return all currently running protocol instances,  current implementation returns only protocols for given era and user hasn't any calls to understand what era he needs,

2022-01-31 10:55 UTC, sgladkov commented
One more issue: tests are failed to build now:
`/home/travis/build/LATOKEN/lachain/test/Lachain.CoreTest/RPC/HTTP/Web3/Web3BlockchainServiceTest.cs(104,31): error CS7036: There is no argument given that corresponds to the required formal parameter 'consensusManager' of 'BlockchainServiceWeb3.BlockchainServiceWeb3(ITransactionManager, IBlockManager, ITransactionPool, IStateManager, ISnapshotIndexRepository, INetworkManager, INodeRetrieval, ISystemContractReader, IConsensusManager)' [/home/travis/build/LATOKEN/lachain/test/Lachain.CoreTest/Lachain.CoreTest.csproj]`

2022-01-31 10:56 UTC, dushyantb commented
> One more issue: tests are failed to build now: `/home/travis/build/LATOKEN/lachain/test/Lachain.CoreTest/RPC/HTTP/Web3/Web3BlockchainServiceTest.cs(104,31): error CS7036: There is no argument given that corresponds to the required formal parameter 'consensusManager' of 'BlockchainServiceWeb3.BlockchainServiceWeb3(ITransactionManager, IBlockManager, ITransactionPool, IStateManager, ISnapshotIndexRepository, INetworkManager, INodeRetrieval, ISystemContractReader, IConsensusManager)' [/home/travis/build/LATOKEN/lachain/test/Lachain.CoreTest/Lachain.CoreTest.csproj]`

yes... looking into that only

2022-02-09 14:05 UTC, dushyantb commented
> Can you please rebase this to the current dev ?

it is already rebased with the current dev

2022-02-09 14:16 UTC, HMAshiqulIslam commented
https://github.com/LATOKEN/lachain/pull/179/files
should this PR change 17 files ?

2022-02-09 14:29 UTC, dushyantb commented
due to circular rebase, it has removed the `dev` rebase... fixed the code

2022-02-09 14:50 UTC, HMAshiqulIslam commented on src/Lachain.Core/Consensus/ConsensusManager.cs
> +            return _eras[CurrentEra];
It's possible that currentEra is null for a long period of time during the start of the machine. You can trigger it locally like this. 
(1) Start 4 nodes. Stop node-1 immediately.
(2) Wait till other blocks generate 100 blocks. 
(3) Start node-1. Now call "la_consensusState". The rpc call will throw exceptions. 

So, it's better to check if this _eras has "CurrentEra" or not and return null if it does not exist.

2022-02-09 14:55 UTC, HMAshiqulIslam commented on src/Lachain.Core/RPC/HTTP/Web3/BlockchainServiceWeb3.cs
> +        private JArray GetConsensusState(long era)
Should we remove this argument ? A program does not know the current era.

2022-02-10 07:51 UTC, HMAshiqulIslam commented on src/Lachain.Core/Consensus/ConsensusManager.cs
> +        {
Should we lock _eras before accessing it ?

2022-02-10 10:30 UTC, dushyantb commented on src/Lachain.Core/RPC/HTTP/Web3/BlockchainServiceWeb3.cs
> +                        ["era"] = id.Era
fixed

2022-02-10 12:56 UTC, HMAshiqulIslam approved these changes
LGTM

2022-02-10 13:27 UTC, sgladkov approved these changes

2022-02-10 13:27 UTC, merged