Change signature algorithm for private API methods
LATOKEN/lachain pull request #193
Opened 2022-02-15 04:05 UTC by kazunetakeda25

Now we sign request body as a whole,  but it is not safe,  body contains spaces,  tabs,  line breaks, and other symbols that can be added or removed during transfer from client to the server. We should construct some string whose format will be predefined in hex view,  smth like this - https://api.latoken.com/doc/v2/#section/Authorization/Signature,  as an example we can use 'method' + "args,  separated with commas"

2022-02-16 12:12 UTC, kazunetakeda25 commented
Hi @sgladkov 
Test repository is here: https://github.com/LATOKEN/lachain-esdca-auth-demo

2022-02-16 14:39 UTC, sgladkov requested changes

2022-02-16 14:39 UTC, sgladkov commented on src/Lachain.Core/RPC/HTTP/HttpService.cs
> +            if(timeSpan.TotalMinutes >= 30)
We should check this header for private methods only

2022-02-16 14:39 UTC, sgladkov commented on src/Lachain.Core/RPC/HTTP/HttpService.cs
> +                catch(Exception e)
Don't add format changes to the functional pull request please

2022-02-16 14:39 UTC, sgladkov commented on src/Lachain.Core/RPC/HTTP/HttpService.cs
> +                string[] bodyParams = bodyPlainText.Split(";");
It is a wrong way to get message to sign. You have `body` here,  already parsed,  you can construct message to sign from it directly smth like `var msgToSign = body['method'] + serialize(body['params']) + timestamp`

2022-02-17 16:18 UTC, sgladkov approved these changes

2022-02-17 16:18 UTC, merged